name: Claude Code - Generate PR

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt to guide Claude Code for changes'
        required: true
        type: string
      base_branch:
        description: 'Branch to create PR into (default: main)'
        required: false
        default: 'main'
        type: string
      target_branch:
        description: 'Branch name for new changes (optional, auto-generate if empty)'
        required: false
        type: string

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code

      - name: Create new branch (if specified)
        run: |
          if [ -n "${{ github.event.inputs.target_branch }}" ]; then
            git checkout -b "${{ github.event.inputs.target_branch }}"
            echo "NEW_BRANCH=${{ github.event.inputs.target_branch }}" >> $GITHUB_ENV
          else
            export GENERATED_BRANCH="claude-pr-$(date +%s)"
            git checkout -b "$GENERATED_BRANCH"
            echo "NEW_BRANCH=$GENERATED_BRANCH" >> $GITHUB_ENV
          fi

      - name: Run Claude Code with Prompt
        run: |
          export ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          claude -p - --allowedTools "Bash(*)" Edit Write << 'EOF'
Do not ask for permission or any questions. I cannot respond. You must make all decisions yourself. You can use any tool you think you need to use. ${{ github.event.inputs.prompt }}
EOF

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin "$NEW_BRANCH"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Claude Code PR: ${{ github.event.inputs.prompt }}'
          body: 'This PR was generated by Claude Code via GitHub Actions.'
          base: ${{ github.event.inputs.base_branch }}
          branch: ${{ env.NEW_BRANCH }}
          labels: ai-generated

      - name: Create PR data artifact
        if: steps.create-pr.outputs.pull-request-number
        run: |
          mkdir -p pr-data
          cat << EOF > pr-data/pr-info.json
          {
            "prUrl": "${{ steps.create-pr.outputs.pull-request-url }}",
            "prNumber": "${{ steps.create-pr.outputs.pull-request-number }}"
          }
          EOF

      - name: Upload PR data artifact
        if: steps.create-pr.outputs.pull-request-number
        uses: actions/upload-artifact@v4
        with:
          name: pr-data
          path: pr-data/pr-info.json
          retention-days: 1
          if-no-files-found: error
